"""Embed the browser's exact demo file mapping for native BBS sessions.

Usage: .venv/bin/python tools/door_demo.py OUT.c GWBASIC.EXE GAMES_DIR BOOTLOGO_IMAGE ROGUE_EXE VZ_IMAGE KERMIT_EXE [MSDOS_DIR [VC405_DIR [HACK_DIR]]]
No directory walk of a previously generated drive: stale build files must never
quietly enter the door. web_demo owns the complete content list and generator.
"""

from pathlib import Path
import json
import sys

from embed import array
from vcini import VcIni
from web_demo import demo_files


ROOT = Path(__file__).resolve().parents[1]


def default_ini() -> bytes:
    """Door-only settings, without changing the native/browser shipped setup.

    VCDATA.INC's WCB saves WinShortPath and FiltAttr for each panel. F86_00
    toggles hidden/system attribute bits together; HidDirs governs tree panels.
    VcIni derives every offset, capacity and attribute bit from the listing.
    """
    ini = VcIni((ROOT / "data/VC.INI").read_bytes())
    if not ini.checksum_ok:
        raise ValueError("the source VC.INI must have a valid checksum")
    hidden_system = ini.sym["fa_HIDDEN"] | ini.sym["fa_SYSTEM"]
    for panel in (0, 1):
        ini.set_panel_path(panel, "H:\\")
        ini.set_panel(panel, "WinTyp", ini.sym["p_File"])
        ini.set_panel(panel, "Visible", 1)
        ini.set_panel(panel, "FiltAttr", ini.panel(panel, "FiltAttr") & ~hidden_system)
    ini.set_main("HidDirs", 0)
    return bytes(ini.data)


def source(files: dict[str, bytes]) -> str:
    lines = ['/* Generated by tools/door_demo.py; do not edit. */',
             '#include "door_demo.h"', '']
    table = []
    for index, (name, contents) in enumerate(files.items()):
        lines.extend(array(f"door_file_{index}", contents))
        # JSON string escaping is also C escaping for our UTF-8 DOS paths.
        quoted = json.dumps(name, ensure_ascii=False)
        table.append(f"  {{{quoted}, door_file_{index}, {len(contents)}u}},")
    lines.extend(['', 'const EmbeddedFile door_demo_files[] = {', *table, '};',
                  f'const int door_demo_file_count = {len(files)};', ''])
    # Internal VC configuration is deliberately outside the browser's H: map.
    # The runtime installs it under .VC/ instead of exposing a separate drive.
    ini = default_ini()
    lines.extend(array("door_ini_data", ini))
    lines.extend(['const EmbeddedFile door_default_ini = {',
                  f'  "VC.INI", door_ini_data, {len(ini)}u', '};', ''])
    return '\n'.join(lines)


def main() -> None:
    if len(sys.argv) not in (8, 9, 10, 11):
        raise SystemExit(__doc__)
    files = demo_files(*(Path(arg) for arg in sys.argv[2:]))
    Path(sys.argv[1]).write_text(source(files), encoding="utf-8")
    print(f"Door demo: {len(files)} files, {sum(map(len, files.values())):,} bytes")


if __name__ == "__main__":
    main()
