"""Publish immutable lazy-module names and the exact names compiled into VC.

Usage: .venv/bin/python tools/web_modules.py WORK_DIRECTORY PUBLISH_DIRECTORY
The unversioned inputs stay in WORK_DIRECTORY, outside the deployed site.
"""
from hashlib import sha256
import os
from pathlib import Path
import re
import sys
import tempfile


PROGRAMS = ("gwbasic", "bootlogo", "rogue", "hack", "vz", "kermit",
            "command", "edlin", "debug", "find", "more", "sort", "fc",
            "vc405", "vcsetup405")
GENERATED_NAME = re.compile(r"(?:" + "|".join(PROGRAMS) + r")(?:\.[0-9a-f]{12})?\.wasm")
# Retire old brief-33 bundles on incremental builds too. DOS file assets
# now all come from embed.py's single per-file, first-open mechanism.
LEGACY_ASSET_NAME = re.compile(r"(?:hack|source)-files\.[0-9a-f]{12}\.bin")


def update(path: Path, data: bytes) -> None:
    """Atomic replacement, preserving mtime when the content did not change."""
    if path.is_symlink():
        raise ValueError(f"Refusing to replace symlink: {path}")
    if path.exists() and path.read_bytes() == data:
        return
    path.parent.mkdir(parents=True, exist_ok=True)
    descriptor, temporary = tempfile.mkstemp(prefix=f".{path.name}.", dir=path.parent)
    try:
        with os.fdopen(descriptor, "wb") as stream:
            stream.write(data)
        os.chmod(temporary, 0o644)
        os.replace(temporary, path)
    finally:
        Path(temporary).unlink(missing_ok=True)


def publish(work: Path, destination: Path) -> str:
    modules = {name: (work / f"{name}.wasm").read_bytes() for name in PROGRAMS}
    digest = sha256()
    for name, data in modules.items():
        digest.update(name.encode("ascii") + b"\0")
        digest.update(len(data).to_bytes(8, "little"))
        digest.update(data)
    # Hash actual side bytes, not just sources or flags. An old main may
    # still find this generation after a main-only deploy, but then all its
    # side bytes are identical; incompatible new bytes necessarily get a
    # different path. The page/main ?v= stamp is computed independently.
    version = digest.hexdigest()[:12]
    names = {name: f"{name}.{version}.wasm" for name in PROGRAMS}
    for name, data in modules.items():
        update(destination / names[name], data)
    header = "/* Generated by tools/web_modules.py; do not edit. */\n"
    header += "".join(f'#define WEB_MODULE_{name.upper()} "{filename}"\n'
                      for name, filename in names.items())
    update(work / "web_program_names.h", header.encode("ascii"))

    # Replacing the site must make old side URLs 404, even after an incremental
    # local build. Retire ONLY our recognized generated names, and keep
    # their bytes outside the publish directory for recovery if needed.
    for path in sorted(destination.iterdir()):
        if (path.name in names.values() or
                not (GENERATED_NAME.fullmatch(path.name) or LEGACY_ASSET_NAME.fullmatch(path.name))):
            continue
        if not path.is_file() or path.is_symlink():
            raise ValueError(f"Refusing to retire non-regular generated module: {path}")
        data = path.read_bytes()
        retired = work / "retired-modules" / f"{path.name}.{sha256(data).hexdigest()}"
        retired.parent.mkdir(parents=True, exist_ok=True)
        if retired.exists():
            if retired.read_bytes() != data:
                raise ValueError(f"Refusing to overwrite different retired module: {retired}")
            path.unlink()  # an identical recoverable copy already exists
        else:
            path.rename(retired)
        print(f"web modules: retired {path} to {retired}")
    return version


def main() -> None:
    if len(sys.argv) != 3:
        raise SystemExit(__doc__)
    version = publish(Path(sys.argv[1]), Path(sys.argv[2]))
    print(f"web modules: published {len(PROGRAMS)} immutable side names ({version})")


if __name__ == "__main__":
    main()
