"""Emit native C statements, not a bytecode interpreter, for listing instructions.

The only instruction decoder runs here, at build time.  The generated helpers
implement arithmetic and memory primitives; neither they nor the dispatcher
inspect guest instruction bytes.  An isolated-instruction entry point uses the
same emitter as the complete image, but returns instead of following a goto.
"""

from __future__ import annotations

from bisect import bisect_left
import json
import re
from typing import Iterable

from capstone.x86 import X86_OP_IMM, X86_OP_MEM, X86_OP_REG


class EmissionError(ValueError):
    """A relocation cannot be represented without changing its meaning."""


class UnsupportedInstruction(ValueError):
    """An instruction must become an explicit runtime fault."""


def emit_prelude() -> str:
    """Common, header-only helpers for images and one-instruction tests.

    Effective addresses wrap before a memory access. Unicorn's word accesses
    then use consecutive physical bytes, including at effective offset FFFF.
    The fixed cpu.h word helpers instead wrap each byte, so deliberately do
    not use those helpers here. The public state/layout headers stay unchanged.
    """
    return r'''/* Generated by translator; do not edit. */
#include <stdint.h>
#include <stddef.h>
#include "cpu.h"
#include "image.h"

static inline uint16_t tr_rd16a(uint32_t a) {
    return (uint16_t)(mem[a] | ((uint16_t)mem[a + 1] << 8));
}
static inline uint16_t tr_rd16(uint16_t s, uint16_t o) {
    return tr_rd16a(lin(s, o));
}
static inline void tr_wr16(uint16_t s, uint16_t o, uint16_t v) {
    uint32_t a = lin(s, o);
    CPU_NOTE_WRITE(a); mem[a] = (uint8_t)v;
    CPU_NOTE_WRITE(a + 1); mem[a + 1] = (uint8_t)(v >> 8);
}
static inline uint32_t tr_far(uint16_t s, uint16_t o) {
    uint32_t a = lin(s, o);
    return tr_rd16a(a) | ((uint32_t)tr_rd16a(a + 2) << 16);
}
static inline void tr_push(uint16_t v) {
    cpu.sp = (uint16_t)(cpu.sp - 2);
    tr_wr16(cpu.ss, cpu.sp, v);
}
static inline uint16_t tr_pop(void) {
    uint16_t v = tr_rd16(cpu.ss, cpu.sp);
    cpu.sp = (uint16_t)(cpu.sp + 2);
    return v;
}
static inline uint32_t tr_mask(unsigned bits) {
    return bits == 8 ? 0xffu : 0xffffu;
}
static inline void tr_szp(uint32_t v, unsigned bits) {
    v &= tr_mask(bits);
    cpu.sf = (uint8_t)((v >> (bits - 1)) & 1u);
    cpu.zf = (v == 0);
    cpu.pf = (uint8_t)(!__builtin_parity(v & 0xffu));
}
static inline uint16_t tr_add(uint32_t a, uint32_t b, unsigned carry, unsigned bits) {
    uint32_t mask = tr_mask(bits), sign = 1u << (bits - 1);
    uint32_t full = a + b + carry, r = full & mask;
    cpu.cf = (full > mask);
    cpu.af = ((a ^ b ^ r) & 0x10u) != 0;
    cpu.of = ((~(a ^ b) & (a ^ r)) & sign) != 0;
    tr_szp(r, bits);
    return (uint16_t)r;
}
static inline uint16_t tr_sub(uint32_t a, uint32_t b, unsigned borrow, unsigned bits) {
    uint32_t sign = 1u << (bits - 1);
    uint32_t r = (a - b - borrow) & tr_mask(bits);
    cpu.cf = (a < b + borrow);
    cpu.af = ((a ^ b ^ r) & 0x10u) != 0;
    cpu.of = (((a ^ b) & (a ^ r)) & sign) != 0;
    tr_szp(r, bits);
    return (uint16_t)r;
}
static inline uint16_t tr_logic(uint32_t r, unsigned bits) {
    cpu.cf = 0; cpu.of = 0; cpu.af = 0;
    tr_szp(r, bits);
    return (uint16_t)(r & tr_mask(bits));
}
static inline uint16_t tr_shl(uint32_t v, unsigned n, unsigned bits) {
    n &= 31u;
    if (!n) return (uint16_t)v;
    uint32_t r = (v << n) & tr_mask(bits);
    cpu.cf = n <= bits ? (uint8_t)((v >> (bits - n)) & 1u) : 0;
    cpu.of = (uint8_t)(((r >> (bits - 1)) & 1u) ^ cpu.cf);
    cpu.af = 0;
    tr_szp(r, bits);
    return (uint16_t)r;
}
static inline uint16_t tr_shr(uint32_t v, unsigned n, unsigned bits) {
    n &= 31u;
    if (!n) return (uint16_t)v;
    uint32_t r = v >> n;
    cpu.cf = n <= bits ? (uint8_t)((v >> (n - 1)) & 1u) : 0;
    /* OF is defined only for one bit; Unicorn clears it for larger counts. */
    cpu.of = n == 1 ? (uint8_t)((v >> (bits - 1)) & 1u) : 0;
    cpu.af = 0;
    tr_szp(r, bits);
    return (uint16_t)r;
}
static inline uint16_t tr_sar(uint32_t v, unsigned n, unsigned bits) {
    n &= 31u;
    if (!n) return (uint16_t)v;
    uint32_t mask = tr_mask(bits), sign = v >> (bits - 1);
    uint32_t r = n >= bits ? (sign ? mask : 0)
        : ((v >> n) | (sign ? (mask << (bits - n)) : 0)) & mask;
    cpu.cf = (uint8_t)(n >= bits ? sign : ((v >> (n - 1)) & 1u));
    cpu.of = 0; cpu.af = 0;
    tr_szp(r, bits);
    return (uint16_t)r;
}
static inline uint16_t tr_rol(uint32_t v, unsigned count, unsigned bits) {
    unsigned masked = count & 31u, n = masked % bits;
    if (!masked) return (uint16_t)v;
    uint32_t r = n ? ((v << n) | (v >> (bits - n))) & tr_mask(bits) : v;
    cpu.cf = (uint8_t)(r & 1u);
    cpu.of = (uint8_t)(((r >> (bits - 1)) & 1u) ^ cpu.cf);
    return (uint16_t)r;
}
static inline uint16_t tr_ror(uint32_t v, unsigned count, unsigned bits) {
    unsigned masked = count & 31u, n = masked % bits;
    if (!masked) return (uint16_t)v;
    uint32_t r = n ? ((v >> n) | (v << (bits - n))) & tr_mask(bits) : v;
    cpu.cf = (uint8_t)((r >> (bits - 1)) & 1u);
    cpu.of = (uint8_t)(((r >> (bits - 1)) ^ (r >> (bits - 2))) & 1u);
    return (uint16_t)r;
}
static inline uint16_t tr_rcl(uint32_t v, unsigned count, unsigned bits) {
    unsigned n = (count & 31u) % (bits + 1);
    if (!n) return (uint16_t)v;
    uint32_t mask = tr_mask(bits), original = v;
    while (n--) {
        unsigned carry = (v >> (bits - 1)) & 1u;
        v = ((v << 1) | cpu.cf) & mask;
        cpu.cf = (uint8_t)carry;
    }
    cpu.of = (uint8_t)(((original ^ v) >> (bits - 1)) & 1u);
    return (uint16_t)v;
}
static inline uint16_t tr_rcr(uint32_t v, unsigned count, unsigned bits) {
    unsigned n = (count & 31u) % (bits + 1);
    if (!n) return (uint16_t)v;
    uint32_t original = v;
    while (n--) {
        unsigned carry = v & 1u;
        v = (v >> 1) | ((uint32_t)cpu.cf << (bits - 1));
        cpu.cf = (uint8_t)carry;
    }
    cpu.of = (uint8_t)(((original ^ v) >> (bits - 1)) & 1u);
    return (uint16_t)v;
}
'''


_REGISTERS = {
    "ax": "cpu.a.x", "al": "cpu.a.l", "ah": "cpu.a.h",
    "bx": "cpu.b.x", "bl": "cpu.b.l", "bh": "cpu.b.h",
    "cx": "cpu.c.x", "cl": "cpu.c.l", "ch": "cpu.c.h",
    "dx": "cpu.d.x", "dl": "cpu.d.l", "dh": "cpu.d.h",
    **{r: f"cpu.{r}" for r in ("si", "di", "bp", "sp", "es", "cs", "ss", "ds")},
}

_CONDITIONS = {
    "ja": "!cpu.cf && !cpu.zf", "jae": "!cpu.cf",
    "jb": "cpu.cf", "jbe": "cpu.cf || cpu.zf",
    "je": "cpu.zf", "jne": "!cpu.zf",
    "jg": "!cpu.zf && cpu.sf == cpu.of", "jge": "cpu.sf == cpu.of",
    "jl": "cpu.sf != cpu.of", "jle": "cpu.zf || cpu.sf != cpu.of",
    "jo": "cpu.of", "jno": "!cpu.of", "js": "cpu.sf", "jns": "!cpu.sf",
    "jp": "cpu.pf", "jnp": "!cpu.pf",
}


def _unwrapped_ip(off: int) -> str:
    # int64_t also makes an out-of-image negative relative target well-defined.
    # rt_code_delta is nonzero only while code copied elsewhere runs.
    return f"((int64_t)loadseg * 16 + ({off}) + rt_code_delta - (int64_t)cpu.cs * 16)"


def _ip(off: int) -> str:
    return f"(uint16_t){_unwrapped_ip(off)}"


class _InstructionEmitter:
    def __init__(self, record, relocations: Iterable[int], targets: set[int] | None = None):
        self.record = record
        self.insn = record.insn
        self.off = record.off
        self.targets = targets or set()
        self.raw = bytes(self.insn.bytes) if self.insn is not None else b""
        self.ops = list(self.insn.operands) if self.insn is not None else []
        self.mnemonic = self.insn.mnemonic.split()[-1] if self.insn is not None else "invalid"
        self.addresses: dict[int, tuple[str, str]] = {}
        self.setup: list[str] = []
        # The public step-emission API accepts any iterable, not just an image
        # loader's already-sorted relocation table.
        ordered = tuple(sorted(relocations))
        at = bisect_left(ordered, self.off - 1)
        self.relocations = set()
        while at < len(ordered) and ordered[at] < self.off + len(self.raw):
            self.relocations.add(ordered[at] - self.off)
            at += 1
        self._validate_relocations()

    def _validate_relocations(self) -> None:
        if not self.relocations:
            return
        allowed = set()
        if self.mnemonic in ("lcall", "ljmp") and self.ops and self.ops[0].type == X86_OP_IMM:
            allowed.add(len(self.raw) - 2)
        elif self.mnemonic == "enter":
            # Capstone describes only ENTER's last (nesting-level) immediate.
            allowed.add(len(self.raw) - 3)
        elif self.insn is not None and self.insn.imm_size == 2:
            allowed.add(self.insn.imm_offset)
        bad = self.relocations - allowed
        if bad:
            where = self.off + min(bad)
            raise EmissionError(
                f"relocation at image offset 0x{where:x} is not an immediate or "
                f"far-pointer segment field of instruction 0x{self.off:x}"
            )

    def reg(self, reg_id: int) -> str:
        name = self.insn.reg_name(reg_id)
        try:
            return _REGISTERS[name]
        except KeyError as exc:
            raise UnsupportedInstruction(f"register {name}") from exc

    def address(self, index: int) -> tuple[str, str]:
        if index in self.addresses:
            return self.addresses[index]
        op = self.ops[index]
        if op.type != X86_OP_MEM:
            raise UnsupportedInstruction("expected a memory operand")
        m = op.mem
        base = self.insn.reg_name(m.base) if m.base else None
        idx = self.insn.reg_name(m.index) if m.index else None
        segment = self.reg(m.segment) if m.segment else (
            "cpu.ss" if base in ("bp", "sp") or idx in ("bp", "sp") else "cpu.ds"
        )
        terms = [str(m.disp)]
        if m.base:
            terms.append(self.reg(m.base))
        if m.index:
            terms.append(f"({self.reg(m.index)} * {m.scale})")
        seg, ea = f"s{index}", f"e{index}"
        self.setup.extend((f"uint16_t {seg} = {segment};", f"uint16_t {ea} = (uint16_t)({' + '.join(terms)});"))
        self.addresses[index] = seg, ea
        return seg, ea

    def read(self, index: int) -> str:
        op = self.ops[index]
        if op.type == X86_OP_REG:
            return self.reg(op.reg)
        if op.type == X86_OP_IMM:
            value = op.imm & (0xff if op.size == 1 else 0xffff)
            if self.insn.imm_offset in self.relocations:
                return f"(uint16_t)(0x{value:04x} + loadseg)"
            return f"0x{value:x}u"
        if op.type == X86_OP_MEM:
            seg, ea = self.address(index)
            if op.size == 1:
                return f"rd8({seg}, {ea})"
            if op.size == 2:
                return f"tr_rd16({seg}, {ea})"
        raise UnsupportedInstruction(f"operand {index} width {op.size}")

    def write(self, index: int, value: str) -> str:
        op = self.ops[index]
        if op.size not in (1, 2):
            raise UnsupportedInstruction(f"operand width {op.size}")
        cast = f"(uint{op.size * 8}_t)({value})"
        if op.type == X86_OP_REG:
            return f"{self.reg(op.reg)} = {cast};"
        if op.type == X86_OP_MEM:
            seg, ea = self.address(index)
            fn = "wr8" if op.size == 1 else "tr_wr16"
            return f"{fn}({seg}, {ea}, {cast});"
        raise UnsupportedInstruction("write to a non-register/non-memory operand")

    def transfer(self, target: int) -> list[str]:
        if target in self.targets:
            # CS and loadseg have paragraph-aligned bases. If the current
            # instruction is executable, every address in that same paragraph
            # is also in its CS window; no runtime guard is needed there.
            if target // 16 == self.off // 16:
                return [f"goto L_{target:x};"]
            # A CS alias can put a relative transfer (or fallthrough) across
            # IP=0000/FFFF. Its wrapped physical target is then 64 KiB away
            # from this static image label and must go through the dispatcher.
            return [f"if ((uint64_t){_unwrapped_ip(target)} <= 0xffffu) goto L_{target:x};",
                    f"cpu.ip = {_ip(target)};", "return 0;"]
        return [f"cpu.ip = {_ip(target)};", "return 0;"]

    def near_target(self) -> int:
        size = self.insn.imm_size
        start = self.insn.imm_offset
        if size not in (1, 2):
            raise UnsupportedInstruction("non-16-bit relative transfer")
        delta = int.from_bytes(self.raw[start:start + size], "little", signed=True)
        return self.off + len(self.raw) + delta

    def relative_transfer(self, tick_backward: bool = False) -> list[str]:
        if self.insn.imm_offset in self.relocations:
            # Unusual but legal: the loader relocates the displacement word.
            # Its target is no longer statically known, even for a near CALL.
            start = self.insn.imm_offset
            value = int.from_bytes(self.raw[start:start + 2], "little")
            code = [f"uint16_t displacement = (uint16_t)(0x{value:04x} + loadseg);",
                    f"uint16_t target_ip = (uint16_t)({_ip(self.off + len(self.raw))} + displacement);"]
            if tick_backward:
                code.append(f"if (target_ip <= {_ip(self.off)}) RT_TICK();")
            return code + ["cpu.ip = target_ip;", "return 0;"]
        target = self.near_target()
        code = ["RT_TICK();"] if tick_backward and target <= self.off else []
        return code + self.transfer(target)

    def fault(self, reason: str) -> list[str]:
        message = f"image offset 0x{self.off:x}: {reason} ({self.raw.hex(' ')})"
        return [f"cpu.ip = {_ip(self.off)};", f"rt_fault({json.dumps(message)});"]

    def divide_error(self) -> list[str]:
        return [f"cpu_int(0, {_ip(self.off)});", "return 0;"]

    def string_body(self, op: str) -> list[str]:
        width = 1 if op.endswith("b") else 2
        accumulator = "cpu.a.l" if width == 1 else "cpu.a.x"
        read = "rd8" if width == 1 else "tr_rd16"
        write = "wr8" if width == 1 else "tr_wr16"
        source = {0x26: "cpu.es", 0x2e: "cpu.cs", 0x36: "cpu.ss", 0x3e: "cpu.ds"}.get(
            self.insn.prefix[1], "cpu.ds"
        )
        kind = op[:-1]
        result = []
        if kind == "movs":
            result.append(f"{write}(cpu.es, cpu.di, {read}({source}, cpu.si));")
        elif kind == "stos":
            result.append(f"{write}(cpu.es, cpu.di, {accumulator});")
        elif kind == "lods":
            result.append(f"{accumulator} = {read}({source}, cpu.si);")
        elif kind == "cmps":
            result.append(f"tr_sub({read}({source}, cpu.si), {read}(cpu.es, cpu.di), 0, {width * 8});")
        elif kind == "scas":
            result.append(f"tr_sub({accumulator}, {read}(cpu.es, cpu.di), 0, {width * 8});")
        elif kind == "ins":
            result.append(f"{write}(cpu.es, cpu.di, port_in{width * 8}(cpu.d.x));")
        elif kind == "outs":
            result.append(f"port_out{width * 8}(cpu.d.x, {read}({source}, cpu.si));")
        else:
            raise UnsupportedInstruction(op)
        if kind in ("movs", "lods", "cmps", "outs"):
            result.append(f"cpu.si = (uint16_t)(cpu.si + (cpu.df ? -{width} : {width}));")
        if kind in ("movs", "stos", "cmps", "scas", "ins"):
            result.append(f"cpu.di = (uint16_t)(cpu.di + (cpu.df ? -{width} : {width}));")
        rep = self.insn.prefix[0]
        if rep in (0xf2, 0xf3):
            repeated = ["while (cpu.c.x != 0) {"]
            repeated.extend("    " + line for line in result)
            repeated.extend(("    cpu.c.x--;", "    RT_TICK();"))
            if kind in ("cmps", "scas"):
                repeated.append("    if (" + ("!cpu.zf" if rep == 0xf3 else "cpu.zf") + ") break;")
            repeated.append("}")
            return repeated
        return result

    def semantics(self) -> tuple[list[str], bool]:
        """Return statements and whether they always transfer control."""
        op = self.mnemonic
        if self.insn is None:
            return self.fault("undecodable instruction"), True
        if self.insn.addr_size != 2 or 0x66 in self.insn.prefix:
            raise UnsupportedInstruction("32-bit address/operand-size prefix")
        if op == "mov":
            return [self.write(0, self.read(1))], False
        if op in ("movzx", "movsx"):
            source = self.read(1)
            if op == "movsx":
                source = f"(int{self.ops[1].size * 8}_t)({source})"
            return [self.write(0, source)], False
        if op == "xchg":
            a, b = self.read(0), self.read(1)
            return [f"uint16_t a = {a}, b = {b};", self.write(0, "b"), self.write(1, "a")], False
        if op == "lea":
            segment, ea = self.address(1)
            return [f"(void){segment};", self.write(0, ea)], False
        if op in ("lds", "les"):
            seg, ea = self.address(1)
            return [f"uint32_t pointer = tr_far({seg}, {ea});", self.write(0, "pointer"),
                    f"cpu.{op[1:]} = (uint16_t)(pointer >> 16);"], False
        if op in ("add", "adc", "sub", "sbb", "cmp", "and", "or", "xor", "test"):
            bits = self.ops[0].size * 8
            if bits not in (8, 16):
                raise UnsupportedInstruction("ALU width")
            a, b = self.read(0), self.read(1)
            code = [f"uint16_t a = {a}, b = {b};"]
            if op in ("add", "adc", "sub", "sbb", "cmp"):
                helper = "tr_add" if op in ("add", "adc") else "tr_sub"
                carry = "cpu.cf" if op in ("adc", "sbb") else "0"
                code.append(f"uint16_t r = {helper}(a, b, {carry}, {bits});")
            else:
                operator = {"and": "&", "test": "&", "or": "|", "xor": "^"}[op]
                code.append(f"uint16_t r = tr_logic(a {operator} b, {bits});")
            if op not in ("cmp", "test"):
                code.append(self.write(0, "r"))
            else:
                code.append("(void)r;")
            return code, False
        if op in ("inc", "dec", "neg", "not"):
            bits = self.ops[0].size * 8
            a = self.read(0)
            if op == "not":
                return [self.write(0, f"~({a})")], False
            if op == "neg":
                return [f"uint16_t r = tr_sub(0, {a}, 0, {bits});", self.write(0, "r")], False
            helper = "tr_add" if op == "inc" else "tr_sub"
            return ["uint8_t old_cf = cpu.cf;", f"uint16_t r = {helper}({a}, 1, 0, {bits});",
                    "cpu.cf = old_cf;", self.write(0, "r")], False
        if op in ("shl", "sal", "shr", "sar", "rol", "ror", "rcl", "rcr"):
            bits = self.ops[0].size * 8
            a, count = self.read(0), self.read(1)
            helper = "shl" if op == "sal" else op
            return [f"uint16_t r = tr_{helper}({a}, {count}, {bits});", self.write(0, "r")], False
        if op in ("mul", "imul"):
            bits = self.ops[0].size * 8
            if bits not in (8, 16):
                raise UnsupportedInstruction("multiply width")
            if len(self.ops) == 1:
                a = "cpu.a.l" if bits == 8 else "cpu.a.x"
                b = self.read(0)
            elif len(self.ops) == 2:
                a, b = self.read(0), self.read(1)
            else:
                a, b = self.read(1), self.read(2)
            if op == "imul":
                code = [f"int32_t product = (int32_t)(int{bits}_t)({a}) * (int{bits}_t)({b});",
                        f"cpu.cf = cpu.of = (product != (int{bits}_t)product);"]
            else:
                code = [f"uint32_t product = (uint32_t)({a}) * ({b});",
                        f"cpu.cf = cpu.of = ((product >> {bits}) != 0);"]
            code.extend((f"tr_szp((uint16_t)product, {bits});", "cpu.af = 0;"))
            if len(self.ops) > 1:
                code.append(self.write(0, "product"))
            elif bits == 8:
                code.append("cpu.a.x = (uint16_t)product;")
            else:
                code.extend(("cpu.a.x = (uint16_t)product;", "cpu.d.x = (uint16_t)((uint32_t)product >> 16);"))
            return code, False
        if op in ("div", "idiv"):
            bits = self.ops[0].size * 8
            divisor = self.read(0)
            if bits not in (8, 16):
                raise UnsupportedInstruction("divide width")
            if op == "div":
                dividend = "cpu.a.x" if bits == 8 else "(((uint32_t)cpu.d.x << 16) | cpu.a.x)"
                code = [f"uint32_t divisor = {divisor}, dividend = {dividend};", "if (divisor == 0) {"]
                code.extend("    " + line for line in self.divide_error())
                code.extend(("}", "uint32_t quotient = dividend / divisor, remainder = dividend % divisor;",
                             f"if (quotient > {0xff if bits == 8 else 0xffff}u) {{"))
            else:
                dividend = "(int16_t)cpu.a.x" if bits == 8 else "(int32_t)(((uint32_t)cpu.d.x << 16) | cpu.a.x)"
                code = [f"int64_t divisor = (int{bits}_t)({divisor}), dividend = {dividend};", "if (divisor == 0) {"]
                code.extend("    " + line for line in self.divide_error())
                code.extend(("}", "int64_t quotient = dividend / divisor, remainder = dividend % divisor;",
                             f"if (quotient < {-1 << (bits - 1)} || quotient > {(1 << (bits - 1)) - 1}) {{"))
            code.extend("    " + line for line in self.divide_error())
            code.append("}")
            if bits == 8:
                code.extend(("cpu.a.l = (uint8_t)quotient;", "cpu.a.h = (uint8_t)remainder;"))
            else:
                code.extend(("cpu.a.x = (uint16_t)quotient;", "cpu.d.x = (uint16_t)remainder;"))
            return code, False
        if op in ("cbw", "cwde") and self.insn.opcode[0] == 0x98:
            return ["cpu.a.x = (uint16_t)(int16_t)(int8_t)cpu.a.l;"], False
        if op in ("cwd", "cdq") and self.insn.opcode[0] == 0x99:
            return ["cpu.d.x = (cpu.a.x & 0x8000u) ? 0xffffu : 0;"], False
        if op == "push":
            return [f"tr_push({self.read(0)});"], False
        if op == "pop":
            return ["uint16_t value = tr_pop();", self.write(0, "value")], False
        if op in ("pushf", "pushfw"):
            return ["tr_push(flags_get());"], False
        if op in ("popf", "popfw"):
            return ["flags_set(tr_pop());"], False
        if op in ("pushaw", "pusha"):
            return ["uint16_t old_sp = cpu.sp;"] + [f"tr_push({r});" for r in
                ("cpu.a.x", "cpu.c.x", "cpu.d.x", "cpu.b.x", "old_sp", "cpu.bp", "cpu.si", "cpu.di")], False
        if op in ("popaw", "popa"):
            return [f"{r} = tr_pop();" if r else "(void)tr_pop();" for r in
                    ("cpu.di", "cpu.si", "cpu.bp", None, "cpu.b.x", "cpu.d.x", "cpu.c.x", "cpu.a.x")], False
        if op == "enter":
            allocation, level = self.ops[0].imm & 0xffff, self.ops[1].imm & 31
            if len(self.raw) - 3 in self.relocations:
                allocation = f"(uint16_t)(0x{allocation:04x} + loadseg)"
            code = ["tr_push(cpu.bp);", "uint16_t frame = cpu.sp;"]
            if level:
                code.extend((f"for (unsigned i = 1; i < {level}; ++i) {{",
                             "    cpu.bp = (uint16_t)(cpu.bp - 2);",
                             "    tr_push(tr_rd16(cpu.ss, cpu.bp));", "}", "tr_push(frame);"))
            code.extend(("cpu.bp = frame;", f"cpu.sp = (uint16_t)(cpu.sp - {allocation});"))
            return code, False
        if op == "leave":
            return ["cpu.sp = cpu.bp;", "cpu.bp = tr_pop();"], False
        if op in _CONDITIONS:
            code = [f"if ({_CONDITIONS[op]}) {{"]
            code.extend("    " + line for line in self.relative_transfer(tick_backward=True))
            code.append("}")
            return code, False
        if op in ("loop", "loope", "loopne", "jcxz"):
            code = [] if op == "jcxz" else ["cpu.c.x--;"]
            code.append("RT_TICK();")
            condition = {"loop": "cpu.c.x != 0", "loope": "cpu.c.x != 0 && cpu.zf",
                         "loopne": "cpu.c.x != 0 && !cpu.zf", "jcxz": "cpu.c.x == 0"}[op]
            code.append(f"if ({condition}) {{")
            code.extend("    " + line for line in self.relative_transfer())
            code.append("}")
            return code, False
        if op in ("call", "jmp"):
            if self.ops[0].type == X86_OP_IMM:
                code = [f"tr_push({_ip(self.off + len(self.raw))});"] if op == "call" else []
                return code + self.relative_transfer(tick_backward=op == "jmp"), True
            target = self.read(0)
            code = [f"uint16_t target = {target};"]
            if op == "call":
                code.append(f"tr_push({_ip(self.off + len(self.raw))});")
            else:
                code.append(f"if (target <= {_ip(self.off)}) RT_TICK();")
            return code + ["cpu.ip = target;", "return 0;"], True
        if op in ("lcall", "ljmp"):
            if self.ops[0].type == X86_OP_IMM:
                segment = int.from_bytes(self.raw[-2:], "little")
                offset = int.from_bytes(self.raw[-4:-2], "little")
                seg_expr = f"(uint16_t)(0x{segment:04x} + loadseg)" if len(self.raw) - 2 in self.relocations else f"0x{segment:04x}u"
                code = [f"uint16_t target_cs = {seg_expr}, target_ip = 0x{offset:04x}u;"]
            else:
                seg, ea = self.address(0)
                code = [f"uint32_t pointer = tr_far({seg}, {ea});",
                        "uint16_t target_cs = (uint16_t)(pointer >> 16), target_ip = (uint16_t)pointer;"]
            if op == "lcall":
                code.extend((f"uint16_t return_ip = {_ip(self.off + len(self.raw))};",
                             "tr_push(cpu.cs);", "tr_push(return_ip);"))
            else:
                code.append(f"if (lin(target_cs, target_ip) <= lin(cpu.cs, {_ip(self.off)})) RT_TICK();")
            return code + ["cpu.cs = target_cs;", "cpu.ip = target_ip;", "return 0;"], True
        if op in ("ret", "retf", "iret"):
            if op == "retf":
                # Unicorn's RETF reads one consecutive m16:16 stack pointer;
                # unlike IRET, its second word does not wrap the old SP first.
                code = ["uint32_t pointer = tr_far(cpu.ss, cpu.sp);",
                        "cpu.sp = (uint16_t)(cpu.sp + 4);",
                        "cpu.ip = (uint16_t)pointer;",
                        "cpu.cs = (uint16_t)(pointer >> 16);"]
            else:
                code = ["cpu.ip = tr_pop();"]
            if op == "iret":
                code.append("cpu.cs = tr_pop();")
            if op == "iret":
                code.append("flags_set(tr_pop());")
            elif self.ops:
                code.append(f"cpu.sp = (uint16_t)(cpu.sp + {self.read(0)});")
            return code + ["return 0;"], True
        if op in ("int", "int3", "into", "int1"):
            number = {"int3": 3, "into": 4, "int1": 1}.get(op)
            if number is None:
                number = self.ops[0].imm & 0xff
            code = [f"cpu_int({number}, {_ip(self.off + len(self.raw))});", "return 0;"]
            if op == "into":
                return ["if (cpu.of) {"] + ["    " + line for line in code] + ["}"], False
            return code, True
        if op in ("movsb", "movsw", "stosb", "stosw", "lodsb", "lodsw", "cmpsb", "cmpsw", "scasb", "scasw", "insb", "insw", "outsb", "outsw"):
            return self.string_body(op), False
        if op in ("xlatb", "xlat"):
            seg = {0x26: "cpu.es", 0x2e: "cpu.cs", 0x36: "cpu.ss", 0x3e: "cpu.ds"}.get(self.insn.prefix[1], "cpu.ds")
            return [f"cpu.a.l = rd8({seg}, (uint16_t)(cpu.b.x + cpu.a.l));"], False
        if op == "in":
            return [self.write(0, f"port_in{self.ops[0].size * 8}({self.read(1)})")], False
        if op == "out":
            return [f"port_out{self.ops[1].size * 8}({self.read(0)}, {self.read(1)});"], False
        if op in ("clc", "stc", "cmc", "cld", "std", "cli", "sti"):
            return [{"clc": "cpu.cf = 0;", "stc": "cpu.cf = 1;", "cmc": "cpu.cf ^= 1;",
                     "cld": "cpu.df = 0;", "std": "cpu.df = 1;", "cli": "cpu.ifl = 0;", "sti": "cpu.ifl = 1;"}[op]], False
        if op == "lahf":
            return ["cpu.a.h = (uint8_t)flags_get();"], False
        if op == "sahf":
            return [f"cpu.{flag} = (cpu.a.h >> {bit}) & 1u;" for flag, bit in
                    (("cf", 0), ("pf", 2), ("af", 4), ("zf", 6), ("sf", 7))], False
        if op == "salc":
            return ["cpu.a.l = cpu.cf ? 0xffu : 0;"], False
        if op in ("aam", "aad"):
            radix = self.raw[-1]
            if op == "aam":
                if radix == 0:
                    return self.divide_error(), True
                code = [f"cpu.a.h = cpu.a.l / {radix};", f"cpu.a.l %= {radix};"]
            else:
                code = [f"cpu.a.l = (uint8_t)(cpu.a.h * {radix} + cpu.a.l);", "cpu.a.h = 0;"]
            return code + ["tr_szp(cpu.a.l, 8);", "cpu.cf = cpu.af = cpu.of = 0;"], False
        if op in ("nop", "wait", "fwait", "pause", "lock"):
            return [], False
        if op == "hlt":
            return self.fault("HLT"), True
        raise UnsupportedInstruction(f"unsupported instruction {self.insn.mnemonic} {self.insn.op_str}")

    def emit(self) -> list[str]:
        try:
            statements, terminal = self.semantics()
        except UnsupportedInstruction as exc:
            self.setup = []
            statements, terminal = self.fault(str(exc)), True
        if not terminal:
            statements += self.transfer(self.off + len(self.raw))
        return self.setup + statements


def emit_instruction_function(record, relocations: Iterable[int], symbol: str) -> str:
    """Emit one externally callable step, with the full-image semantics."""
    if not re.fullmatch(r"[A-Za-z_][A-Za-z_0-9]*", symbol):
        raise ValueError(f"invalid C symbol {symbol!r}")
    body = _InstructionEmitter(record, relocations).emit()
    return f"int {symbol}(uint16_t loadseg) {{\n" + "\n".join("    " + line for line in body) + "\n}\n"


def emit_image(layout, name: str, symbol: str) -> str:
    """Emit the load module, metadata, PROC chunks, and exact-start dispatcher."""
    if not re.fullmatch(r"[A-Za-z_][A-Za-z_0-9]*", symbol):
        raise ValueError(f"invalid C symbol {symbol!r}")
    image = layout.image
    relocations = tuple(sorted(image.relocations))
    output = [emit_prelude()]
    for chunk in layout.chunks:
        name_comment = chunk.name.replace("*/", "* /")
        output.append(f"/* Listing chunk {name_comment}. */\nstatic int chunk_{chunk.index}(uint32_t off, uint16_t loadseg) {{")
        output.append("    switch (off) {")
        for record in chunk.instructions:
            output.append(f"    case 0x{record.off:x}u: goto L_{record.off:x};")
        output.append("    default: return -1;\n    }")
        targets = {record.off for record in chunk.instructions}
        for record in chunk.instructions:
            asm = f"{record.insn.mnemonic} {record.insn.op_str}" if record.insn is not None else "invalid"
            output.append(f"L_{record.off:x}: {{ /* {asm.replace('*/', '* /')} */")
            output.extend("    " + line for line in _InstructionEmitter(record, relocations, targets).emit())
            output.append("}")
        output.append("}\n")
    output.append("static const struct { uint32_t off; int (*fn)(uint32_t, uint16_t); } starts[] = {")
    for record in sorted(layout.instructions, key=lambda instruction: instruction.off):
        output.append(f"    {{0x{record.off:x}u, chunk_{record.chunk.index}}},")
    if not layout.instructions:
        output.append("    {0u, NULL},")
    output.append("};")
    output.extend(("static int run(uint32_t off, uint16_t loadseg) {",
                   f"    size_t lo = 0, hi = {len(layout.instructions)}u;",
                   "    while (lo < hi) {",
                   "        size_t mid = lo + (hi - lo) / 2;",
                   "        if (starts[mid].off < off) lo = mid + 1; else hi = mid;",
                   "    }",
                   f"    if (lo == {len(layout.instructions)}u || starts[lo].off != off) return -1;",
                   "    return starts[lo].fn(off, loadseg);", "}"))
    output.append("static const uint8_t image_bytes[] = {")
    for at in range(0, len(image.data), 16):
        output.append("    " + ", ".join(f"0x{b:02x}" for b in image.data[at:at + 16]) + ",")
    if not image.data:
        output.append("    0,")
    output.append("};\nstatic const uint32_t image_relocations[] = {")
    for at in range(0, len(relocations), 12):
        output.append("    " + ", ".join(f"0x{r:x}u" for r in relocations[at:at + 12]) + ",")
    if not relocations:
        output.append("    0,")
    output.append("};")
    output.append(f"const Image {symbol} = {{")
    output.extend((f"    .name = {json.dumps(name)}, .is_exe = {int(image.is_exe)},",
                   f"    .bytes = image_bytes, .size = {len(image.data)}u,",
                   f"    .relocs = image_relocations, .nrelocs = {len(relocations)}u,",
                   f"    .hdr_cs = {image.hdr_cs}, .hdr_ip = {image.hdr_ip},",
                   f"    .hdr_ss = {image.hdr_ss}, .hdr_sp = {image.hdr_sp},",
                   f"    .min_alloc = {image.min_alloc}, .max_alloc = {image.max_alloc},",
                   "    .run = run,", "};\n"))
    return "\n".join(output)
